In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('Movie_classification.csv')

In [3]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  \
0          223.840  Thriller              23            494       48000   
1          243.456     Drama              42            462       43200   
2         2022.400    Comedy              38            458       69400   
3          225.344     Drama              45            472       66800   
4          225.792     Drama              55            395       72400   

   Start_Tech_Oscar  
0                 1  
1                 0  
2                 1  
3                 1  
4                 1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           494 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

### This shows that time taken column has some NaN values as compared to other columns.

In [5]:
df.rename(columns={'Marketing expense':'Marketing_expense'})

Marketing_expense  Production expense  Multiplex coverage     Budget  \
0              20.1264               59.62               0.462  36524.125   
1              20.5462               69.14               0.531  35668.655   
2              20.5458               69.14               0.531  39912.675   
3              20.6474               59.36               0.542  38873.890   
4              21.3810               59.36               0.542  39701.585   
..                 ...                 ...                 ...        ...   
501            21.2526               78.86               0.427  36624.115   
502            20.9054               78.86               0.427  33996.600   
503            21.2152               78.86               0.427  38751.680   
504            22.1918               78.86               0.427  37740.670   
505            20.9482               78.86               0.427  33496.650   

     Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0           138.7               7.825                8.095            7.910   
1           152.4               7.505                7.650            7.440   
2           134.6               7.485                7.570            7.495   
3           119.3               6.895                7.035            6.920   
4           127.7               6.920                7.070            6.815   
..            ...                 ...                  ...              ...   
501         142.6               8.680                8.775            8.620   
502         150.2               8.780                8.945            8.770   
503         164.5               8.830                8.970            8.855   
504         162.8               8.730                8.845            8.800   
505         154.3               8.640                8.880            8.680   

     Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0              7.995           7.94         527367          YES      109.60   
1              7.470           7.44         494055           NO      146.64   
2              7.515           7.44         547051           NO      147.88   
3              7.020           8.26         516279          YES      185.36   
4              7.070           8.26         531448           NO      176.48   
..               ...            ...            ...          ...         ...   
501            8.970           6.80         492480           NO      186.96   
502            8.930           7.80         482875          YES      132.24   
503            9.010           7.80         532239           NO      109.56   
504            8.845           6.80         496077          YES      158.80   
505            8.790           6.80         518438          YES      205.60   

     Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  \
0            223.840  Thriller              23            494       48000   
1            243.456     Drama              42            462       43200   
2           2022.400    Comedy              38            458       69400   
3            225.344     Drama              45            472       66800   
4            225.792     Drama              55            395       72400   
..               ...       ...             ...            ...         ...   
501          243.584    Action              27            561       44800   
502          263.296    Action              20            600       41200   
503          243.824    Comedy              31            576       47800   
504          303.520    Comedy              47            607       44000   
505          203.040    Comedy              45            604       38000   

     Start_Tech_Oscar  
0                   1  
1                   0  
2                   1  
3                   1  
4                   1  
..                ...  
501                 0  
502                 0  
503                 0  
504              

In [6]:
df.rename(columns={'Production expense':'Production_expense'})

Marketing expense  Production_expense  Multiplex coverage     Budget  \
0              20.1264               59.62               0.462  36524.125   
1              20.5462               69.14               0.531  35668.655   
2              20.5458               69.14               0.531  39912.675   
3              20.6474               59.36               0.542  38873.890   
4              21.3810               59.36               0.542  39701.585   
..                 ...                 ...                 ...        ...   
501            21.2526               78.86               0.427  36624.115   
502            20.9054               78.86               0.427  33996.600   
503            21.2152               78.86               0.427  38751.680   
504            22.1918               78.86               0.427  37740.670   
505            20.9482               78.86               0.427  33496.650   

     Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0           138.7               7.825                8.095            7.910   
1           152.4               7.505                7.650            7.440   
2           134.6               7.485                7.570            7.495   
3           119.3               6.895                7.035            6.920   
4           127.7               6.920                7.070            6.815   
..            ...                 ...                  ...              ...   
501         142.6               8.680                8.775            8.620   
502         150.2               8.780                8.945            8.770   
503         164.5               8.830                8.970            8.855   
504         162.8               8.730                8.845            8.800   
505         154.3               8.640                8.880            8.680   

     Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0              7.995           7.94         527367          YES      109.60   
1              7.470           7.44         494055           NO      146.64   
2              7.515           7.44         547051           NO      147.88   
3              7.020           8.26         516279          YES      185.36   
4              7.070           8.26         531448           NO      176.48   
..               ...            ...            ...          ...         ...   
501            8.970           6.80         492480           NO      186.96   
502            8.930           7.80         482875          YES      132.24   
503            9.010           7.80         532239           NO      109.56   
504            8.845           6.80         496077          YES      158.80   
505            8.790           6.80         518438          YES      205.60   

     Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  \
0            223.840  Thriller              23            494       48000   
1            243.456     Drama              42            462       43200   
2           2022.400    Comedy              38            458       69400   
3            225.344     Drama              45            472       66800   
4            225.792     Drama              55            395       72400   
..               ...       ...             ...            ...         ...   
501          243.584    Action              27            561       44800   
502          263.296    Action              20            600       41200   
503          243.824    Comedy              31            576       47800   
504          303.520    Comedy              47            607       44000   
505          203.040    Comedy              45            604       38000   

     Start_Tech_Oscar  
0                   1  
1                   0  
2                   1  
3                   1  
4                   1  
..                ...  
501                 0  
502                 0  
503                 0  
504              

In [7]:
df.Time_taken=df.Time_taken.fillna(df.Time_taken.mean())

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           506 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

### This shows that we have filled the NaN values in Time Taken column by mean value 

In [9]:
x=df.iloc[:,0:-1] #This line makes the value of x to be consisting of all the values except the last column.
x.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  
0          223.840  Thriller              23            494       48000  
1          243.456     Drama              42            462       43200  
2         2022.400    Comedy              38            458       69400  
3          225.344     Drama              45            472       66800  
4          225.792     Drama              55            395       72400

In [10]:
x=pd.get_dummies(x)
x.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  ...  Twitter_hastags  Avg_age_actors  \
0            7.995           7.94  ...          223.840              23   
1            7.470           7.44  ...          243.456              42   
2            7.515           7.44  ...         2022.400              38   
3            7.020           8.26  ...          225.344              45   
4            7.070           8.26  ...          225.792              55   

   Num_multiplex  Collection  3D_available_NO  3D_available_YES  Genre_Action  \
0            494       48000                0                 1             0   
1            462       43200                1                 0             0   
2            458       69400                1                 0             0   
3            472       66800                0                 1             0   
4            395       72400                1                 0             0   

   Genre_Comedy  Genre_Drama  Genre_Thriller  
0             0            0               1  
1             0            1               0  
2             1            0               0  
3             0            1               0  
4             0            1               0  

[5 rows x 22 columns]

### We can see that over here, the values of 3D availability and genre of the film have been converted into binary form.

In [12]:
del x['3D_available_NO']
del x['Genre_Thriller']

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)
x

array([[-0.41978194, -1.2879095 ,  0.14421743, ..., -0.40400296,
        -0.66452648, -0.48699468],
       [-0.41733926, -0.59338101,  0.74026221, ..., -0.40400296,
        -0.66452648,  2.05341054],
       [-0.41734159, -0.59338101,  0.74026221, ..., -0.40400296,
         1.50483093, -0.48699468],
       ...,
       [-0.41344658,  0.11573841, -0.15812412, ..., -0.40400296,
         1.50483093, -0.48699468],
       [-0.40776407,  0.11573841, -0.15812412, ..., -0.40400296,
         1.50483093, -0.48699468],
       [-0.41500016,  0.11573841, -0.15812412, ..., -0.40400296,
         1.50483093, -0.48699468]])

In [14]:
y = df.loc[:,['Start_Tech_Oscar']].values
y

array([[1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
    

### Here, we see that values of x are in the row format whereas y contains values in the format of a column. So, we will be changing the format of y in order to have a co-ordination between x and y.

In [16]:
y=y.reshape(-1)
y

array([1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,

In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [19]:
x_train

array([[-0.37884533, -0.72032214,  0.41200566, ..., -0.40400296,
        -0.66452648, -0.48699468],
       [-0.402042  , -0.04768006,  1.22400869, ...,  2.4752294 ,
        -0.66452648, -0.48699468],
       [-0.40733349, -0.90562701,  1.09443374, ..., -0.40400296,
         1.50483093, -0.48699468],
       ...,
       [-0.40294739, -0.16440754,  0.06647246, ...,  2.4752294 ,
        -0.66452648, -0.48699468],
       [-0.39383653, -0.61672651,  0.92166714, ..., -0.40400296,
        -0.66452648, -0.48699468],
       [-0.40432525, -1.03402724,  0.38609067, ..., -0.40400296,
        -0.66452648, -0.48699468]])

In [20]:
y_test

array([0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1], dtype=int64)