In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df=pd.read_csv("Movie_classification.csv")

In [8]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  \
0          223.840  Thriller              23            494       48000   
1          243.456     Drama              42            462       43200   
2         2022.400    Comedy              38            458       69400   
3          225.344     Drama              45            472       66800   
4          225.792     Drama              55            395       72400   

   Start_Tech_Oscar  
0                 1  
1                 0  
2                 1  
3                 1  
4                 1

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           494 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

In [10]:
df['Time_taken'].fillna(value=df['Time_taken'].mean(),inplace= True)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           506 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

In [12]:
df=pd.get_dummies(df,columns=['3D_available','Genre'])

In [13]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  ...  Avg_age_actors  Num_multiplex  \
0            7.995           7.94  ...              23            494   
1            7.470           7.44  ...              42            462   
2            7.515           7.44  ...              38            458   
3            7.020           8.26  ...              45            472   
4            7.070           8.26  ...              55            395   

   Collection  Start_Tech_Oscar  3D_available_NO  3D_available_YES  \
0       48000                 1                0                 1   
1       43200                 0                1                 0   
2       69400                 1                1                 0   
3       66800                 1                0                 1   
4       72400                 1                1                 0   

   Genre_Action  Genre_Comedy  Genre_Drama  Genre_Thriller  
0             0             0            0               1  
1             0             0            1               0  
2             0             1            0               0  
3             0             0            1               0  
4             0             0            1               0  

[5 rows x 23 columns]

In [14]:
del df['3D_available_NO']

In [15]:
x=df.iloc[:,0:-1] #all columns except Start_tech oscar
x.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  ...  Time_taken  Twitter_hastags  \
0            7.995           7.94  ...      109.60          223.840   
1            7.470           7.44  ...      146.64          243.456   
2            7.515           7.44  ...      147.88         2022.400   
3            7.020           8.26  ...      185.36          225.344   
4            7.070           8.26  ...      176.48          225.792   

   Avg_age_actors  Num_multiplex  Collection  Start_Tech_Oscar  \
0              23            494       48000                 1   
1              42            462       43200                 0   
2              38            458       69400                 1   
3              45            472       66800                 1   
4              55            395       72400                 1   

   3D_available_YES  Genre_Action  Genre_Comedy  Genre_Drama  
0                 1             0             0            0  
1                 0             0             0            1  
2                 0             0             1            0  
3                 1             0             0            1  
4                 0             0             0            1  

[5 rows x 21 columns]

In [16]:
type(x)

pandas.core.frame.DataFrame

In [17]:
x.shape

(506, 21)

In [18]:
y=df['Start_Tech_Oscar']
y.head()

0    1
1    0
2    1
3    1
4    1
Name: Start_Tech_Oscar, dtype: int64

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2, random_state=0)

In [21]:
x_train.shape

(404, 21)

In [22]:
x_test.shape

(102, 21)

In [23]:
from sklearn.preprocessing import StandardScaler

In [24]:
sc=StandardScaler().fit(x_train)

In [25]:
x_train_std=sc.transform(x_train)# we compressed the whole upper line here to transform

In [26]:
x_test_std=sc.transform(x_test)

In [27]:
x_test_std

array([[-0.40835869, -1.12872913,  0.83336883, ..., -0.40529635,
         1.50268577, -0.48525664],
       [ 0.71925111,  0.9988844 , -0.65283979, ..., -0.40529635,
         1.50268577, -0.48525664],
       [-0.40257488,  0.39610829,  0.05115377, ..., -0.40529635,
         1.50268577, -0.48525664],
       ...,
       [-0.3982601 , -0.85812418,  0.89420778, ..., -0.40529635,
        -0.66547513, -0.48525664],
       [-0.39934279, -0.07637654,  0.58132175, ..., -0.40529635,
         1.50268577, -0.48525664],
       [-0.40088071, -0.36702631,  0.31189212, ...,  2.4673304 ,
        -0.66547513, -0.48525664]])

In [28]:
from sklearn import svm

In [29]:
clf_svm_1=svm.SVC(kernel='linear',C=100)
clf_svm_1.fit(x_train_std,y_train)

SVC(C=100, kernel='linear')

In [30]:
y_train_pred=clf_svm_1.predict(x_train_std)
y_test_pred=clf_svm_1.predict(x_test)

In [31]:
y_train_pred

array([1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,

In [32]:
y_test_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [33]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [34]:
confusion_matrix(y_test,y_test_pred)

array([[44,  0],
       [58,  0]], dtype=int64)

In [35]:
accuracy_score(y_test,y_test_pred)

0.43137254901960786

### Polynomial kernel

In [36]:
clf_svm_p2=svm.SVC(kernel='poly',degree=2,C=0.1)
clf_svm_p2.fit(x_train_std,y_train)

SVC(C=0.1, degree=2, kernel='poly')

In [37]:
y_train_pred=clf_svm_p2.predict(x_train_std)
y_test_pred=clf_svm_p2.predict(x_test_std)

In [38]:
accuracy_score(y_test,y_test_pred)

0.5588235294117647

### Grid Search

In [39]:
from sklearn.model_selection import GridSearchCV

In [40]:
params = {'C':(0.001,0.005,0.01,0.05, 0.1, 0.5, 1, 5, 10, 50,100,500,1000)}

In [41]:
clf_svm_p4=svm.SVC(kernel='rbf')

In [42]:
svm_grid_rbf=GridSearchCV(clf_svm_p4,params,n_jobs=-1,cv=10,verbose=1,scoring='accuracy')

In [43]:
svm_grid_rbf.fit(x_train_std,y_train)

Fitting 10 folds for each of 13 candidates, totalling 130 fits


GridSearchCV(cv=10, estimator=SVC(), n_jobs=-1,
             param_grid={'C': (0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50,
                               100, 500, 1000)},
             scoring='accuracy', verbose=1)

In [45]:
svm_grid_rbf.best_params_

{'C': 1}

In [47]:
rbfsvm_clf=svm_grid_rbf.best_estimator_

In [49]:
accuracy_score(y_test,rbfsvm_clf.predict(x_test_std))

0.9901960784313726

### Radial kernel

In [50]:
clf_svm_p3=svm.SVC(kernel='rbf',degree=2,C=0.1)
clf_svm_p3.fit(x_train_std,y_train)

SVC(C=0.1, degree=2)

In [51]:
y_train_pred=clf_svm_p3.predict(x_train_std)
y_test_pred=clf_svm_p3.predict(x_test_std)

In [52]:
accuracy_score(y_test,y_test_pred)

0.9803921568627451

### We can see that radial kernel provides us the best accuracy ,so we will be using this only for the particular dataset.